name: "rtmdet_s"
platform: "onnxruntime_onnx"
max_batch_size: 8
input {
  name: "input"
  data_type: TYPE_FP32
  dims: [3, 640, 640]
}
output {
  name: "boxes"
  data_type: TYPE_FP32
  dims: [100, 4]
}
output {
  name: "scores"
  data_type: TYPE_FP32
  dims: [100]
}
output {
  name: "labels"
  data_type: TYPE_INT64
  dims: [100]
}
instance_group [{ kind: KIND_GPU }]
