name: "optical_flow"
platform: "onnxruntime_onnx"
max_batch_size: 4
input {
  name: "0"
  data_type: TYPE_FP32
  dims: [3, 320, 320]
}
input {
  name: "1"
  data_type: TYPE_FP32
  dims: [3, 320, 320]
}
output {
  name: "flow"
  data_type: TYPE_FP32
  dims: [2, 320, 320]
}
instance_group [{ kind: KIND_CPU }]
