name: "segformer"
platform: "onnxruntime_onnx"
max_batch_size: 8
input {
  name: "pixel_values"
  data_type: TYPE_FP32
  dims: [3, 512, 512]
}
output {
  name: "logits"
  data_type: TYPE_FP32
  dims: [-1, -1, -1]
}
instance_group [{ kind: KIND_GPU }]
